### ISSUE TITLE
Folder structure standard for nodejs projects

### ISSUE THREAD

**Issue by jhenaoz** [arodrigueze/BirthAppServer#2]
You can check this as a reference for the refactor
https://stackoverflow.com/questions/5178334/folder-structure-for-a-node-js-project

actually i prefer the common one that is really used:

**/src
/test**

like coffe script suggestions, this will help to have all your code inside a folder for linter and test commands that scan recursively the folders for do some specific task

**Comment by jhenaoz** [comment]
something like that..
![image](https://user-images.githubusercontent.com/2055110/34889784-536d8f04-f79d-11e7-94e5-e076041fd143.png)

**Comment by arodrigueze** [comment]
Folder structure changed as suggested
